<a href="https://colab.research.google.com/github/subho99/Computational-Data-Science/blob/main/Subhajit_Basistha_M1_AST_11_Solving_Linear_Equations_C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Advanced Certification Program in Computational Data Science
## A program by IISc and TalentSprint
### Assignment: Solving linear equations

## Learning Objectives

At the end of the experiment, you will be able to :

* use computational techniques and algebraic skills essential for the study of systems of linear equations
* use Python libraries, eg. Numpy's `linalg.solve` and Scipy's `scipy.linalg`, to solve linear equation based operations
* model practical problems using linear systems


## Introduction

Linear equations are formalizations of the relationship between variables. It is also possible to consider more than one linear equation using the same variables: this is *a system of equations*.

A **system of equations** is a set of equations describing the relationship between variables. For instance, let’s consider the following example:
$$y = 2x + 1$$
$$y = -0.5x + 3$$

We have two linear equations and they both characterize the relationship between the variables x and y. This is a system with two equations and two variables.

We can convert the two equations into a single vector equation as follows:
<br><br>
<center>
<img src="https://cdn.iisc.talentsprint.com/CDS/Images/eqn_to_vector.png" width = 700 px />
</center>

For further understanding, refer [here](https://towardsdatascience.com/how-do-you-use-numpy-scipy-and-sympy-to-solve-systems-of-linear-equations-9afed2c388af).
<br><br>

Also, linear systems of equations can have either:
- No solution
- One solution
- An infinite number of solutions
<br><br>
<center>
<img src="https://cdn.iisc.talentsprint.com/CDS/Images/diff_solns_for_linear_eqns.png" width=800 px />
</center>

For further understanding, refer [here](https://www.math.ucla.edu/~archristian/notes/linear-algebra/systems-of-linear-equations.pdf).


### Setup Steps:

In [1]:
#@title Please enter your registration id to start: { run: "auto", display-mode: "form" }
Id = "2236624" #@param {type:"string"}

In [2]:
#@title Please enter your password (your registered phone number) to continue: { run: "auto", display-mode: "form" }
password = "8240187807" #@param {type:"string"}

In [3]:
#@title Run this cell to complete the setup for this Notebook
from IPython import get_ipython

ipython = get_ipython()
  
notebook= "M1_AST_11_Solving_Linear_Equations_C" #name of the notebook

def setup():
#  ipython.magic("sx pip3 install torch")  

    from IPython.display import HTML, display
    display(HTML('<script src="https://dashboard.talentsprint.com/aiml/record_ip.html?traineeId={0}&recordId={1}"></script>'.format(getId(),submission_id)))
    print("Setup completed successfully")
    return

def submit_notebook():
    ipython.magic("notebook -e "+ notebook + ".ipynb")
    
    import requests, json, base64, datetime

    url = "https://dashboard.talentsprint.com/xp/app/save_notebook_attempts"
    if not submission_id:
      data = {"id" : getId(), "notebook" : notebook, "mobile" : getPassword()}
      r = requests.post(url, data = data)
      r = json.loads(r.text)

      if r["status"] == "Success":
          return r["record_id"]
      elif "err" in r:        
        print(r["err"])
        return None        
      else:
        print ("Something is wrong, the notebook will not be submitted for grading")
        return None
    
    elif getAnswer() and getComplexity() and getAdditional() and getConcepts() and getComments() and getMentorSupport():
      f = open(notebook + ".ipynb", "rb")
      file_hash = base64.b64encode(f.read())

      data = {"complexity" : Complexity, "additional" :Additional, 
              "concepts" : Concepts, "record_id" : submission_id, 
              "answer" : Answer, "id" : Id, "file_hash" : file_hash,
              "notebook" : notebook,
              "feedback_experiments_input" : Comments,
              "feedback_mentor_support": Mentor_support}
      r = requests.post(url, data = data)
      r = json.loads(r.text)
      if "err" in r:        
        print(r["err"])
        return None   
      else:
        print("Your submission is successful.")
        print("Ref Id:", submission_id)
        print("Date of submission: ", r["date"])
        print("Time of submission: ", r["time"])
        print("View your submissions: https://cds.iisc.talentsprint.com/notebook_submissions")
        #print("For any queries/discrepancies, please connect with mentors through the chat icon in LMS dashboard.")
        return submission_id
    else: submission_id
    

def getAdditional():
  try:
    if not Additional: 
      raise NameError
    else:
      return Additional  
  except NameError:
    print ("Please answer Additional Question")
    return None

def getComplexity():
  try:
    if not Complexity:
      raise NameError
    else:
      return Complexity
  except NameError:
    print ("Please answer Complexity Question")
    return None
  
def getConcepts():
  try:
    if not Concepts:
      raise NameError
    else:
      return Concepts
  except NameError:
    print ("Please answer Concepts Question")
    return None
  
  
# def getWalkthrough():
#   try:
#     if not Walkthrough:
#       raise NameError
#     else:
#       return Walkthrough
#   except NameError:
#     print ("Please answer Walkthrough Question")
#     return None
  
def getComments():
  try:
    if not Comments:
      raise NameError
    else:
      return Comments
  except NameError:
    print ("Please answer Comments Question")
    return None
  

def getMentorSupport():
  try:
    if not Mentor_support:
      raise NameError
    else:
      return Mentor_support
  except NameError:
    print ("Please answer Mentor support Question")
    return None

def getAnswer():
  try:
    if not Answer:
      raise NameError 
    else: 
      return Answer
  except NameError:
    print ("Please answer Question")
    return None
  

def getId():
  try: 
    return Id if Id else None
  except NameError:
    return None

def getPassword():
  try:
    return password if password else None
  except NameError:
    return None

submission_id = None
### Setup 
if getPassword() and getId():
  submission_id = submit_notebook()
  if submission_id:
    setup() 
else:
  print ("Please complete Id and Password cells before running setup")



Setup completed successfully


### Import required packages

In [4]:
import numpy as np
from scipy.linalg import solve

### Solving Systems of Linear Equations with Python's Numpy

The ultimate goal of solving a system of linear equations is to find the values of the unknown variables. 

The Numpy library contains the `linalg.solve()` method, which can be used to directly find the solution of a system of linear equations.

#### Solve a system of three linear equations, as shown below:

$$4x + 3y + 2z = 25$$

$$-2x + 2y + 3z = -10$$

$$3x -5y + 2z = -4$$


We can express this system as a matrix equation $A\ *$ X $= b$

In [5]:
# defining the coefficient matrix
A = np.array([[4, 3, 2], 
              [-2, 2, 3], 
              [3, -5, 2]])

# defining the constant value matrix
B = np.array([25, -10, -4])

# use np.linalg.solve to solve for x
X1 = np.linalg.solve(A, B)

# displaying the value of x, y and z
print(X1)

[ 5.  3. -2.]


#### Consider the following three equations and solve:

$x_0 + 2 \times x_1 + x_2 = 4$

$x_1 + x_2 = 3$

$x_0 + x_2 = 5$

In [6]:
# defining the coefficient matrix
A = np.array([[1, 2, 1],
              [0, 1, 1],
              [1, 0, 1]])
# defining the constant value matrix
b = np.array([4, 3, 5])

In [7]:
# use np.linalg.solve to solve for x
x = np.linalg.solve(A, b)

print(x)

[ 1.5 -0.5  3.5]


### `numpy.linalg` vs `scipy.linalg`

NumPy includes some tools for working with linear algebra applications in the numpy.linalg module. However, its typically better to use scipy.linalg for the following reasons:

- scipy.linalg contains all the functions in numpy.linalg plus some extra advanced functions not included in numpy.linalg.

- scipy.linalg is always compiled with support from libraries including routines for performing numerical operations in an optimized way, whereas for numpy.linalg, the use of these libraries (BLAS and LAPACK) is optional. Thus, depending on how you install NumPy, scipy.linalg functions might be faster than the ones from numpy.linalg.

So, in conclusion, considering that scientific and technical applications generally don’t have restrictions regarding dependencies, it’s generally a good idea to install SciPy and use scipy.linalg instead of numpy.linalg.

In the following section, we will use scipy.linalg tools to work with linear systems. We will begin by going through the basics with a straightforward example, and then apply the concepts to a practical problem.

### Solve linear system of equations using `scipy.linalg.solve()`

Linear systems are a useful tool for finding the solution to several important practical problems, including problems related to vehicle traffic, balancing chemical equations, electrical circuits, and polynomial interpolation.

Practical applications generally involve a large number of variables, which makes it infeasible to solve linear systems manually. Luckily, there are some tools that can do this hard work, such as `scipy.linalg.solve()`.

SciPy provides `scipy.linalg.solve()` to solve linear systems quickly and in a reliable way. Let's see how it works. 

Consider the following system:
$$3x_1 + 2x_2 = 12$$
$$2x_1 - 1x_2 = 1$$

In order to use `scipy.linalg.solve()`, we first need to write the linear system as a matrix product:
$$\underbrace{\begin{bmatrix}3 & 2\\2 & -1\end{bmatrix}}_{\text{A}} . \underbrace{\begin{bmatrix} x_1 \\ x_2\end{bmatrix}}_{\text{x}} = \underbrace{\begin{bmatrix} 12 \\ 1\end{bmatrix}}_{\text{b}}$$

Note that we will arrive at the original equations of the system after calculating the matrix product. 

The inputs `scipy.linalg.solve()` expects to solve are the matrix A and the vector b, which we can define using NumPy arrays. This way, we can solve the system using the following code:

In [8]:
from scipy.linalg import solve

# Create the coefficients matrix using a NumPy array
A = np.array([[3, 2], 
              [2, -1]])

# Create the independent terms vector
# To make it a column vector with two lines, we use .reshape((2, 1))
b = np.array([12, 1]).reshape((2, 1))

# Solve the linear system characterized by A and b
x = solve(A, b)
x

array([[2.],
       [3.]])

We can verify the solution to the system by replacing $x_1 = 2$ and $x_2 = 3$ in the original equations.

Now, let's see a practical application of linear systems.

### Building a Meal Plan

Here we will find the proportions of components needed to obtain a certain mixture, by solving with a system of linear equations. Here we will build a meal plan, mixing different foods in order to get a balanced diet.

For that, consider that a balanced diet should include the following:

- 170 units of vitamin A
- 180 units of vitamin B
- 140 units of vitamin C
- 180 units of vitamin D
- 350 units of vitamin E

The task is to find the quantities of each different food in order to obtain the specified amount of vitamins. In the following table, we have the results of analyzing one gram of each food in terms of units of each vitamin:

|Food | Vitamin A| Vitamin B| Vitamin C | Vitamin D | Vitamin E|
|----|----|-------|-------|-------|-----|
| #1 | 1 | 10 | 1 | 2 | 2 |
| #2 | 9 | 1 | 0 | 1 | 1 |
| #3 | 2 | 2 | 5 | 1 | 2 |
| #4 | 1 | 1 | 1 | 2 | 13 |
| #5 | 1 | 1 | 1 | 9 | 2 |
<br>

By denoting food 1 as $x_1$ and so on, and considering that we will mix $x_1$ units of food 1, $x_2$ units of food 2, and so on, we can write an expression for the amount of vitamin A that we would get in the combination. 

Considering a balanced diet should include 170 units of vitamin A, we can use the data from the Vitamin A column to write the following equation:
$$x_1 + 9x_2 + 2x_3 + x_4 + x_5 = 170$$

Repeating the same procedure for vitamins B, C, D, and E, we arrive at the following linear system:
$$\ x_1 + 9x_2 + 2x_3 + x_4 + x_5 = 170$$
$$10x_1 + x_2 + 2x_3 + x_4 + x_5 = 180$$
$$\ \ \ \ \ \ \ \ \ \ \ \ \ x_1 + 5x_3 + x_4 + x_5 = 140$$
$$2x_1 + x_2 + x_3 + 2x_4 + 9x_5 = 180$$
$$2x_1 + x_2 + 2x_3 + 13x_4 + 2x_5 = 350 \ \ \ \ $$

To use `scipy.linalg.solve()`, we have to obtain the coefficients matrix A and the independent terms vector b, which are given by the following:

$$\underbrace{\begin{bmatrix}1 & 9 & 2 & 1 & 1\\10 & 1 & 2 & 1 & 1\\1 & 0 & 5 & 1 & 1\\2 & 1 & 1 & 2 & 9\\2 & 1 & 2 & 13 & 2\end{bmatrix}}_{\text{A}} . \underbrace{\begin{bmatrix} x_1 \\ x_2\\ x_3\\ x_4\\ x_5\end{bmatrix}}_{\text{x}} = \underbrace{\begin{bmatrix} 170 \\ 180\\ 140\\ 180\\ 350\end{bmatrix}}_{\text{b}}$$

Now we just have to use `scipy.linalg.solve()` to find out the quantities $x_1, x_2, ..., x_5$:

In [9]:
# Create the coefficients matrix
A = np.array([[1, 9, 2, 1, 1],
              [10, 1, 2, 1, 1],
              [1, 0, 5, 1, 1],
              [2, 1, 1, 2, 9],
              [2, 1, 2, 13, 2]
              ])

# Create the independent terms vector
b = np.array([170, 180, 140, 180, 350]).reshape((5, 1))

x = solve(A, b)
x

array([[10.],
       [10.],
       [20.],
       [20.],
       [10.]])

This indicates that a balanced diet should include 
- 10 units of food 1, 
- 10 units of food 2, 
- 20 units of food 3, 
- 20 units of food 4, and 
- 10 units of food 5.



### Please answer the questions below to complete the experiment:




Consider the following systems of linear equations:

(a)

$\quad x + y = 12$

$\quad 3x + 3y = 36$

(b)

$\quad 2x + 4y = 8$

$\quad 4x + 2y = 10$

(C)

$\quad 2x + 3y + z = 6$

$\quad x + y + z = 17$

$\quad 4x + 6y + 2z = 13$

In [17]:
#@title Determine which of the above systems has a unique solution: { run: "auto", form-width: "500px", display-mode: "form" }
Answer = "c" #@param ["", "a", "b", "c"]

In [11]:
#@title How was the experiment? { run: "auto", form-width: "500px", display-mode: "form" }
Complexity = "Good, But Not Challenging for me" #@param ["","Too Simple, I am wasting time", "Good, But Not Challenging for me", "Good and Challenging for me", "Was Tough, but I did it", "Too Difficult for me"]


In [12]:
#@title If it was too easy, what more would you have liked to be added? If it was very difficult, what would you have liked to have been removed? { run: "auto", display-mode: "form" }
Additional = "good exercise" #@param {type:"string"}


In [13]:
#@title Can you identify the concepts from the lecture which this experiment covered? { run: "auto", vertical-output: true, display-mode: "form" }
Concepts = "Yes" #@param ["","Yes", "No"]


In [14]:
#@title  Text and image description/explanation and code comments within the experiment: { run: "auto", vertical-output: true, display-mode: "form" }
Comments = "Very Useful" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [15]:
#@title Mentor Support: { run: "auto", vertical-output: true, display-mode: "form" }
Mentor_support = "Very Useful" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [18]:
#@title Run this cell to submit your notebook for grading { vertical-output: true }
try:
  if submission_id:
      return_id = submit_notebook()
      if return_id : submission_id = return_id
  else:
      print("Please complete the setup first.")
except NameError:
  print ("Please complete the setup first.")

Your submission is successful.
Ref Id: 2190
Date of submission:  21 Jan 2023
Time of submission:  19:00:37
View your submissions: https://cds.iisc.talentsprint.com/notebook_submissions
